In [1]:
import pandas as pd

In [2]:
weather_train = pd.read_csv("weather (table 7)_training.csv")
weather_train.shape

(782, 9)

In [6]:
# 观察天气信息的info
weather_train.info()
weather_train.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 782 entries, 0 to 781
Data columns (total 9 columns):
date              782 non-null object
hour              782 non-null int64
pressure          782 non-null float64
sea_pressure      782 non-null float64
wind_direction    782 non-null float64
wind_speed        782 non-null float64
temperature       782 non-null float64
rel_humidity      782 non-null float64
precipitation     782 non-null float64
dtypes: float64(7), int64(1), object(1)
memory usage: 55.1+ KB

,date,hour,pressure,sea_pressure,wind_direction,wind_speed,temperature,rel_humidity,precipitation
0,2016-07-01,0,1000.4,1005.3,225.0,2.1,26.4,94.0,0.0
1,2016-07-01,3,1000.5,1005.3,187.0,2.7,29.0,76.0,0.0
2,2016-07-01,6,998.9,1003.7,212.0,2.9,31.7,67.0,0.0
3,2016-07-01,9,998.7,1003.5,244.0,2.7,31.6,59.0,0.0
4,2016-07-01,12,999.7,1004.5,222.0,1.3,29.9,68.0,0.0
5,2016-07-01,15,1000.0,1004.8,102.0,1.6,27.8,82.0,0.0
6,2016-07-01,18,998.8,1003.6,202.0,1.9,26.0,89.0,0.0
7,2016-07-01,21,1000.2,1005.0,334.0,2.2,25.5,90.0,0.0
8,2016-07-02,0,1001.6,1006.4,315.0,1.8,26.8,82.0,0.0
9,2016-07-02,3,1002.4,1007.2,46.0,3.2,30.0,70.0,0.0

In [7]:
# 观察天气信息的统计特征
weather_train.describe()

,hour,pressure,sea_pressure,wind_direction,wind_speed,temperature,rel_humidity,precipitation
count,782.000000,782.000000,782.000000,782.000000,782.000000,782.000000,782.000000,782.000000
mean,10.500000,1004.032353,1008.907545,10398.617647,2.315217,27.532992,74.253197,0.232353
std,6.866525,5.643326,5.729872,100572.980954,1.230320,4.977435,15.732717,1.453105
min,0.000000,993.400000,998.200000,0.000000,0.000000,14.100000,27.000000,0.000000
25%,6.000000,1000.000000,1004.800000,80.000000,1.500000,23.800000,63.000000,0.000000
50%,10.500000,1002.400000,1007.200000,190.000000,2.000000,27.700000,76.000000,0.000000
75%,15.000000,1007.575000,1012.575000,295.750000,2.900000,31.100000,88.000000,0.000000
max,21.000000,1018.400000,1023.500000,999017.000000,7.500000,39.400000,98.000000,27.200000