In [14]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns
%matplotlib inline

In [15]:
volume_entry_train = pd.read_csv("volume_exit_test_1Soffset0.csv",index_col="Unnamed: 0")
print volume_entry_train.columns
volume_entry_train.head()

Index([u'cargo_count0', u'cargo_count1', u'cargo_count2', u'cargo_count3',
       u'cargo_count4', u'cargo_count5', u'cargo_model0', u'cargo_model1',
       u'cargo_model2', u'cargo_model3', u'cargo_model4', u'cargo_model5',
       u'cargo_model_avg0', u'cargo_model_avg1', u'cargo_model_avg2',
       u'cargo_model_avg3', u'cargo_model_avg4', u'cargo_model_avg5',
       u'etc_count0', u'etc_count1', u'etc_count2', u'etc_count3',
       u'etc_count4', u'etc_count5', u'no_count0', u'no_count1', u'no_count2',
       u'no_count3', u'no_count4', u'no_count5', u'passenger_count0',
       u'passenger_count1', u'passenger_count2', u'passenger_count3',
       u'passenger_count4', u'passenger_count5', u'passenger_model0',
       u'passenger_model1', u'passenger_model2', u'passenger_model3',
       u'passenger_model4', u'passenger_model5', u'passenger_model_avg0',
       u'passenger_model_avg1', u'passenger_model_avg2',
       u'passenger_model_avg3', u'passenger_model_avg4',
       u'passenger_model_avg5', u'vehicle_model0', u'vehicle_model1',
       u'vehicle_model2', u'vehicle_model3', u'vehicle_model4',
       u'vehicle_model5', u'vehicle_model_avg0', u'vehicle_model_avg1',
       u'vehicle_model_avg2', u'vehicle_model_avg3', u'vehicle_model_avg4',
       u'vehicle_model_avg5', u'volume0', u'volume1', u'volume2', u'volume3',
       u'volume4', u'volume5', u'vehicle_all_model', u'cargo_all_model',
       u'passenger_all_model', u'no_all_count', u'cargo_all_count',
       u'passenger_all_count', u'volume_all', u'etc_all_count',
       u'vehicle_all_model_avg', u'cargo_all_model_avg',
       u'passenger_all_model_avg', u'hour', u'minute'],
      dtype='object')

,cargo_count0,cargo_count1,cargo_count2,cargo_count3,cargo_count4,cargo_count5,cargo_model0,cargo_model1,cargo_model2,cargo_model3,...,no_all_count,cargo_all_count,passenger_all_count,volume_all,etc_all_count,vehicle_all_model_avg,cargo_all_model_avg,passenger_all_model_avg,hour,minute
2016-10-18 06:00:00,22.0,24.0,31.0,18.0,26.0,22.0,52.0,68.0,63.0,40.0,...,0.0,143.0,280.0,423.0,98.0,1.470449,2.209790,1.092857,8H,0M
2016-10-18 15:00:00,14.0,16.0,33.0,19.0,18.0,19.0,33.0,26.0,56.0,38.0,...,0.0,119.0,470.0,589.0,137.0,1.244482,1.890756,1.080851,17H,0M
2016-10-19 06:00:00,28.0,13.0,18.0,24.0,21.0,27.0,58.0,33.0,39.0,59.0,...,0.0,131.0,270.0,401.0,93.0,1.453865,2.229008,1.077778,8H,0M
2016-10-19 15:00:00,14.0,17.0,15.0,17.0,9.0,15.0,25.0,34.0,34.0,36.0,...,0.0,87.0,434.0,521.0,134.0,1.214971,1.908046,1.076037,17H,0M
2016-10-20 06:00:00,24.0,15.0,26.0,27.0,20.0,17.0,43.0,36.0,57.0,60.0,...,0.0,129.0,269.0,398.0,85.0,1.364322,1.976744,1.070632,8H,0M

In [19]:
for i in range(len(volume_entry_train.columns)):
    print str(i) + " " + volume_entry_train.columns[i]

0 cargo_count0
1 cargo_count1
2 cargo_count2
3 cargo_count3
4 cargo_count4
5 cargo_count5
6 cargo_model0
7 cargo_model1
8 cargo_model2
9 cargo_model3
10 cargo_model4
11 cargo_model5
12 cargo_model_avg0
13 cargo_model_avg1
14 cargo_model_avg2
15 cargo_model_avg3
16 cargo_model_avg4
17 cargo_model_avg5
18 etc_count0
19 etc_count1
20 etc_count2
21 etc_count3
22 etc_count4
23 etc_count5
24 no_count0
25 no_count1
26 no_count2
27 no_count3
28 no_count4
29 no_count5
30 passenger_count0
31 passenger_count1
32 passenger_count2
33 passenger_count3
34 passenger_count4
35 passenger_count5
36 passenger_model0
37 passenger_model1
38 passenger_model2
39 passenger_model3
40 passenger_model4
41 passenger_model5
42 passenger_model_avg0
43 passenger_model_avg1
44 passenger_model_avg2
45 passenger_model_avg3
46 passenger_model_avg4
47 passenger_model_avg5
48 vehicle_model0
49 vehicle_model1
50 vehicle_model2
51 vehicle_model3
52 vehicle_model4
53 vehicle_model5
54 vehicle_model_avg0
55 vehicle_model_avg1
56 vehicle_model_avg2
57 vehicle_model_avg3
58 vehicle_model_avg4
59 vehicle_model_avg5
60 volume0
61 volume1
62 volume2
63 volume3
64 volume4
65 volume5
66 vehicle_all_model
67 cargo_all_model
68 passenger_all_model
69 no_all_count
70 cargo_all_count
71 passenger_all_count
72 volume_all
73 etc_all_count
74 vehicle_all_model_avg
75 cargo_all_model_avg
76 passenger_all_model_avg
77 hour
78 minute

In [20]:
volume_entry_train = pd.read_csv("volume_exit_train_1Soffset0.csv",index_col="Unnamed: 0")
for i in range(len(volume_entry_train.columns)):
    print str(i) + " " + volume_entry_train.columns[i]

0 cargo_count0
1 cargo_count1
2 cargo_count2
3 cargo_count3
4 cargo_count4
5 cargo_count5
6 cargo_model0
7 cargo_model1
8 cargo_model2
9 cargo_model3
10 cargo_model4
11 cargo_model5
12 cargo_model_avg0
13 cargo_model_avg1
14 cargo_model_avg2
15 cargo_model_avg3
16 cargo_model_avg4
17 cargo_model_avg5
18 etc_count0
19 etc_count1
20 etc_count2
21 etc_count3
22 etc_count4
23 etc_count5
24 no_count0
25 no_count1
26 no_count2
27 no_count3
28 no_count4
29 no_count5
30 passenger_count0
31 passenger_count1
32 passenger_count2
33 passenger_count3
34 passenger_count4
35 passenger_count5
36 passenger_model0
37 passenger_model1
38 passenger_model2
39 passenger_model3
40 passenger_model4
41 passenger_model5
42 passenger_model_avg0
43 passenger_model_avg1
44 passenger_model_avg2
45 passenger_model_avg3
46 passenger_model_avg4
47 passenger_model_avg5
48 vehicle_model0
49 vehicle_model1
50 vehicle_model2
51 vehicle_model3
52 vehicle_model4
53 vehicle_model5
54 vehicle_model_avg0
55 vehicle_model_avg1
56 vehicle_model_avg2
57 vehicle_model_avg3
58 vehicle_model_avg4
59 vehicle_model_avg5
60 volume0
61 volume1
62 volume2
63 volume3
64 volume4
65 volume5
66 y
67 vehicle_all_model
68 cargo_all_model
69 passenger_all_model
70 no_all_count
71 cargo_all_count
72 passenger_all_count
73 volume_all
74 etc_all_count
75 vehicle_all_model_avg
76 cargo_all_model_avg
77 passenger_all_model_avg
78 hour
79 minute